# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.core.exceptions import HttpResponseError
import msrest.serialization


class ErrorAdditionalInfo(msrest.serialization.Model):
    """The resource management error additional info.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: any
    """

    _validation = {
        'type': {'readonly': True},
        'info': {'readonly': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'info': {'key': 'info', 'type': 'object'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorAdditionalInfo, self).__init__(**kwargs)
        self.type = None
        self.info = None


class ErrorDetail(msrest.serialization.Model):
    """The error detail.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.maps.data.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.maps.data.models.ErrorAdditionalInfo]
    """

    _validation = {
        'code': {'readonly': True},
        'message': {'readonly': True},
        'target': {'readonly': True},
        'details': {'readonly': True},
        'additional_info': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'details': {'key': 'details', 'type': '[ErrorDetail]'},
        'additional_info': {'key': 'additionalInfo', 'type': '[ErrorAdditionalInfo]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorDetail, self).__init__(**kwargs)
        self.code = None
        self.message = None
        self.target = None
        self.details = None
        self.additional_info = None


class ErrorResponse(msrest.serialization.Model):
    """Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).

    :param error: The error object.
    :type error: ~azure.maps.data.models.ErrorDetail
    """

    _attribute_map = {
        'error': {'key': 'error', 'type': 'ErrorDetail'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorResponse, self).__init__(**kwargs)
        self.error = kwargs.get('error', None)


class LongRunningOperationResult(msrest.serialization.Model):
    """The response model for a Long-Running Operations API.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param operation_id: The Id for this long-running operation.
    :type operation_id: str
    :ivar status: The status state of the request. Possible values include: "NotStarted",
     "Running", "Failed", "Succeeded".
    :vartype status: str or ~azure.maps.data.models.LroStatus
    :ivar created: The created timestamp.
    :vartype created: str
    :ivar resource_location: The location URI for details about the created resource. This is only
     provided when the request was successfully completed.
    :vartype resource_location: str
    :param error: The error detail.
    :type error: ~azure.maps.data.models.ErrorDetail
    :param warning: The error detail.
    :type warning: ~azure.maps.data.models.ErrorDetail
    """

    _validation = {
        'status': {'readonly': True},
        'created': {'readonly': True},
        'resource_location': {'readonly': True},
    }

    _attribute_map = {
        'operation_id': {'key': 'operationId', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'created': {'key': 'created', 'type': 'str'},
        'resource_location': {'key': 'resourceLocation', 'type': 'str'},
        'error': {'key': 'error', 'type': 'ErrorDetail'},
        'warning': {'key': 'warning', 'type': 'ErrorDetail'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(LongRunningOperationResult, self).__init__(**kwargs)
        self.operation_id = kwargs.get('operation_id', None)
        self.status = None
        self.created = None
        self.resource_location = None
        self.error = kwargs.get('error', None)
        self.warning = kwargs.get('warning', None)


class MapDataDetailInfo(msrest.serialization.Model):
    """Detail information for the data.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar udid: The unique data id for the data.
    :vartype udid: str
    :ivar location: The location of the data. Execute a HTTP ``GET`` on this location to download
     the data.
    :vartype location: str
    :ivar size_in_bytes: The size of the content in bytes.
    :vartype size_in_bytes: long
    :ivar upload_status: The current upload status of the content.
    :vartype upload_status: str
    :ivar data_format: The current data format.
    :vartype data_format: str
    :ivar description: The current description.
    :vartype description: str
    """

    _validation = {
        'udid': {'readonly': True},
        'location': {'readonly': True},
        'size_in_bytes': {'readonly': True},
        'upload_status': {'readonly': True},
        'data_format': {'readonly': True},
        'description': {'readonly': True},
    }

    _attribute_map = {
        'udid': {'key': 'udid', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'size_in_bytes': {'key': 'sizeInBytes', 'type': 'long'},
        'upload_status': {'key': 'uploadStatus', 'type': 'str'},
        'data_format': {'key': 'dataFormat', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(MapDataDetailInfo, self).__init__(**kwargs)
        self.udid = None
        self.location = None
        self.size_in_bytes = None
        self.upload_status = None
        self.data_format = None
        self.description = None


class MapDataListResponse(msrest.serialization.Model):
    """The response model for the Data List API. Returns a list of all the previously uploaded data.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar map_data_list: A list of all the previously uploaded data.
    :vartype map_data_list: list[~azure.maps.data.models.MapDataDetailInfo]
    """

    _validation = {
        'map_data_list': {'readonly': True},
    }

    _attribute_map = {
        'map_data_list': {'key': 'mapDataList', 'type': '[MapDataDetailInfo]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(MapDataListResponse, self).__init__(**kwargs)
        self.map_data_list = None
