# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Optional

from azure.core.exceptions import HttpResponseError
import msrest.serialization


class ErrorAdditionalInfo(msrest.serialization.Model):
    """The resource management error additional info.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: any
    """

    _validation = {
        'type': {'readonly': True},
        'info': {'readonly': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'info': {'key': 'info', 'type': 'object'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorAdditionalInfo, self).__init__(**kwargs)
        self.type = None
        self.info = None


class ErrorDetail(msrest.serialization.Model):
    """The error detail.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.maps.tileset.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.maps.tileset.models.ErrorAdditionalInfo]
    """

    _validation = {
        'code': {'readonly': True},
        'message': {'readonly': True},
        'target': {'readonly': True},
        'details': {'readonly': True},
        'additional_info': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'details': {'key': 'details', 'type': '[ErrorDetail]'},
        'additional_info': {'key': 'additionalInfo', 'type': '[ErrorAdditionalInfo]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorDetail, self).__init__(**kwargs)
        self.code = None
        self.message = None
        self.target = None
        self.details = None
        self.additional_info = None


class ErrorResponse(msrest.serialization.Model):
    """Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).

    :param error: The error object.
    :type error: ~azure.maps.tileset.models.ErrorDetail
    """

    _attribute_map = {
        'error': {'key': 'error', 'type': 'ErrorDetail'},
    }

    def __init__(
        self,
        *,
        error: Optional["ErrorDetail"] = None,
        **kwargs
    ):
        super(ErrorResponse, self).__init__(**kwargs)
        self.error = error


class LongRunningOperationResult(msrest.serialization.Model):
    """The response model for a Long-Running Operations API.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param operation_id: The Id for this long-running operation.
    :type operation_id: str
    :ivar status: The status state of the request. Possible values include: "NotStarted",
     "Running", "Failed", "Succeeded".
    :vartype status: str or ~azure.maps.tileset.models.LroStatus
    :ivar created: The created timestamp.
    :vartype created: str
    :ivar resource_location: The location URI for details about the created resource. This is only
     provided when the request was successfully completed.
    :vartype resource_location: str
    :param error: The error detail.
    :type error: ~azure.maps.tileset.models.ErrorDetail
    :param warning: The error detail.
    :type warning: ~azure.maps.tileset.models.ErrorDetail
    """

    _validation = {
        'status': {'readonly': True},
        'created': {'readonly': True},
        'resource_location': {'readonly': True},
    }

    _attribute_map = {
        'operation_id': {'key': 'operationId', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'created': {'key': 'created', 'type': 'str'},
        'resource_location': {'key': 'resourceLocation', 'type': 'str'},
        'error': {'key': 'error', 'type': 'ErrorDetail'},
        'warning': {'key': 'warning', 'type': 'ErrorDetail'},
    }

    def __init__(
        self,
        *,
        operation_id: Optional[str] = None,
        error: Optional["ErrorDetail"] = None,
        warning: Optional["ErrorDetail"] = None,
        **kwargs
    ):
        super(LongRunningOperationResult, self).__init__(**kwargs)
        self.operation_id = operation_id
        self.status = None
        self.created = None
        self.resource_location = None
        self.error = error
        self.warning = warning


class TilesetDetailInfo(msrest.serialization.Model):
    """Detail information for the data.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar tileset_id: The unique tileset id for the tileset.
    :vartype tileset_id: str
    :ivar ontology: The ontology version of this dataset.
    :vartype ontology: str
    :ivar dataset_id: The unique dataset Id used to create the tileset.
    :vartype dataset_id: str
    :ivar description: The description the caller provided when creating the tileset. Maximum
     length 1024 characters.
    :vartype description: str
    :ivar min_zoom: The lowest tile zoom level tile generated for the tileset.
    :vartype min_zoom: int
    :ivar max_zoom: The highest tile zoom level tile generated for the tileset.
    :vartype max_zoom: int
    :ivar bbox: Bounding box which all features of the tileset lay within. Projection used -
     EPSG:3857. Format : 'minLon, minLat, maxLon, maxLat'.
    :vartype bbox: list[float]
    """

    _validation = {
        'tileset_id': {'readonly': True},
        'ontology': {'readonly': True},
        'dataset_id': {'readonly': True},
        'description': {'readonly': True},
        'min_zoom': {'readonly': True},
        'max_zoom': {'readonly': True},
        'bbox': {'readonly': True},
    }

    _attribute_map = {
        'tileset_id': {'key': 'tilesetId', 'type': 'str'},
        'ontology': {'key': 'ontology', 'type': 'str'},
        'dataset_id': {'key': 'datasetId', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'min_zoom': {'key': 'minZoom', 'type': 'int'},
        'max_zoom': {'key': 'maxZoom', 'type': 'int'},
        'bbox': {'key': 'bbox', 'type': '[float]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(TilesetDetailInfo, self).__init__(**kwargs)
        self.tileset_id = None
        self.ontology = None
        self.dataset_id = None
        self.description = None
        self.min_zoom = None
        self.max_zoom = None
        self.bbox = None


class TilesetListResponse(msrest.serialization.Model):
    """The response model for the Tileset List API. Returns a list of all tilesets.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar tilesets: A list of all tilesets.
    :vartype tilesets: list[~azure.maps.tileset.models.TilesetDetailInfo]
    :ivar next_link: If present, the location of the next page of data.
    :vartype next_link: str
    """

    _validation = {
        'tilesets': {'readonly': True},
        'next_link': {'readonly': True},
    }

    _attribute_map = {
        'tilesets': {'key': 'tilesets', 'type': '[TilesetDetailInfo]'},
        'next_link': {'key': 'nextLink', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(TilesetListResponse, self).__init__(**kwargs)
        self.tilesets = None
        self.next_link = None
