# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import CollectionDefinitionResponse
    from ._models_py3 import CollectionInfo
    from ._models_py3 import CollectionsResponse
    from ._models_py3 import ConformanceResponse
    from ._models_py3 import DefinitionProperties
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import ExtendedGeoJsonFeatureCollection
    from ._models_py3 import ExtendedGeoJsonFeatureCollectionData
    from ._models_py3 import FeatureResponse
    from ._models_py3 import GeoJsonFeature
    from ._models_py3 import GeoJsonFeatureCollection
    from ._models_py3 import GeoJsonFeatureCollectionData
    from ._models_py3 import GeoJsonFeatureData
    from ._models_py3 import GeoJsonGeometry
    from ._models_py3 import GeoJsonGeometryCollection
    from ._models_py3 import GeoJsonGeometryCollectionData
    from ._models_py3 import GeoJsonLineString
    from ._models_py3 import GeoJsonLineStringData
    from ._models_py3 import GeoJsonMultiLineString
    from ._models_py3 import GeoJsonMultiLineStringData
    from ._models_py3 import GeoJsonMultiPoint
    from ._models_py3 import GeoJsonMultiPointData
    from ._models_py3 import GeoJsonMultiPolygon
    from ._models_py3 import GeoJsonMultiPolygonData
    from ._models_py3 import GeoJsonObject
    from ._models_py3 import GeoJsonPoint
    from ._models_py3 import GeoJsonPointData
    from ._models_py3 import GeoJsonPolygon
    from ._models_py3 import GeoJsonPolygonData
    from ._models_py3 import LandingPageResponse
    from ._models_py3 import WfsEndpointLink
except (SyntaxError, ImportError):
    from ._models import CollectionDefinitionResponse  # type: ignore
    from ._models import CollectionInfo  # type: ignore
    from ._models import CollectionsResponse  # type: ignore
    from ._models import ConformanceResponse  # type: ignore
    from ._models import DefinitionProperties  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import ExtendedGeoJsonFeatureCollection  # type: ignore
    from ._models import ExtendedGeoJsonFeatureCollectionData  # type: ignore
    from ._models import FeatureResponse  # type: ignore
    from ._models import GeoJsonFeature  # type: ignore
    from ._models import GeoJsonFeatureCollection  # type: ignore
    from ._models import GeoJsonFeatureCollectionData  # type: ignore
    from ._models import GeoJsonFeatureData  # type: ignore
    from ._models import GeoJsonGeometry  # type: ignore
    from ._models import GeoJsonGeometryCollection  # type: ignore
    from ._models import GeoJsonGeometryCollectionData  # type: ignore
    from ._models import GeoJsonLineString  # type: ignore
    from ._models import GeoJsonLineStringData  # type: ignore
    from ._models import GeoJsonMultiLineString  # type: ignore
    from ._models import GeoJsonMultiLineStringData  # type: ignore
    from ._models import GeoJsonMultiPoint  # type: ignore
    from ._models import GeoJsonMultiPointData  # type: ignore
    from ._models import GeoJsonMultiPolygon  # type: ignore
    from ._models import GeoJsonMultiPolygonData  # type: ignore
    from ._models import GeoJsonObject  # type: ignore
    from ._models import GeoJsonPoint  # type: ignore
    from ._models import GeoJsonPointData  # type: ignore
    from ._models import GeoJsonPolygon  # type: ignore
    from ._models import GeoJsonPolygonData  # type: ignore
    from ._models import LandingPageResponse  # type: ignore
    from ._models import WfsEndpointLink  # type: ignore

from ._maps_wfs_client_enums import (
    GeoJsonGeometryType,
    GeoJsonObjectType,
    GeographicResourceLocation,
    Geography,
)

__all__ = [
    'CollectionDefinitionResponse',
    'CollectionInfo',
    'CollectionsResponse',
    'ConformanceResponse',
    'DefinitionProperties',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'ExtendedGeoJsonFeatureCollection',
    'ExtendedGeoJsonFeatureCollectionData',
    'FeatureResponse',
    'GeoJsonFeature',
    'GeoJsonFeatureCollection',
    'GeoJsonFeatureCollectionData',
    'GeoJsonFeatureData',
    'GeoJsonGeometry',
    'GeoJsonGeometryCollection',
    'GeoJsonGeometryCollectionData',
    'GeoJsonLineString',
    'GeoJsonLineStringData',
    'GeoJsonMultiLineString',
    'GeoJsonMultiLineStringData',
    'GeoJsonMultiPoint',
    'GeoJsonMultiPointData',
    'GeoJsonMultiPolygon',
    'GeoJsonMultiPolygonData',
    'GeoJsonObject',
    'GeoJsonPoint',
    'GeoJsonPointData',
    'GeoJsonPolygon',
    'GeoJsonPolygonData',
    'LandingPageResponse',
    'WfsEndpointLink',
    'GeoJsonGeometryType',
    'GeoJsonObjectType',
    'GeographicResourceLocation',
    'Geography',
]
