# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import BooleanRuleObject
    from ._models_py3 import BooleanTypeStyleRule
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import FeatureStateObject
    from ._models_py3 import FeatureStatesStructure
    from ._models_py3 import NumberRuleObject
    from ._models_py3 import NumberTypeStyleRule
    from ._models_py3 import RangeObject
    from ._models_py3 import StatesetCreatedResponse
    from ._models_py3 import StatesetGetResponse
    from ._models_py3 import StatesetInfoObject
    from ._models_py3 import StatesetListResponse
    from ._models_py3 import StringTypeStyleRule
    from ._models_py3 import StyleObject
    from ._models_py3 import StylesObject
except (SyntaxError, ImportError):
    from ._models import BooleanRuleObject  # type: ignore
    from ._models import BooleanTypeStyleRule  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import FeatureStateObject  # type: ignore
    from ._models import FeatureStatesStructure  # type: ignore
    from ._models import NumberRuleObject  # type: ignore
    from ._models import NumberTypeStyleRule  # type: ignore
    from ._models import RangeObject  # type: ignore
    from ._models import StatesetCreatedResponse  # type: ignore
    from ._models import StatesetGetResponse  # type: ignore
    from ._models import StatesetInfoObject  # type: ignore
    from ._models import StatesetListResponse  # type: ignore
    from ._models import StringTypeStyleRule  # type: ignore
    from ._models import StyleObject  # type: ignore
    from ._models import StylesObject  # type: ignore

from ._maps_featurestate_client_enums import (
    GeographicResourceLocation,
    Geography,
    StyleObjectType,
)

__all__ = [
    'BooleanRuleObject',
    'BooleanTypeStyleRule',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'FeatureStateObject',
    'FeatureStatesStructure',
    'NumberRuleObject',
    'NumberTypeStyleRule',
    'RangeObject',
    'StatesetCreatedResponse',
    'StatesetGetResponse',
    'StatesetInfoObject',
    'StatesetListResponse',
    'StringTypeStyleRule',
    'StyleObject',
    'StylesObject',
    'GeographicResourceLocation',
    'Geography',
    'StyleObjectType',
]
