# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import BufferRequestBody
    from ._models_py3 import BufferResponse
    from ._models_py3 import BufferResponseSummary
    from ._models_py3 import ClosestPointResponse
    from ._models_py3 import ClosestPointResultEntry
    from ._models_py3 import ClosestPointSummary
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import GeoJsonFeature
    from ._models_py3 import GeoJsonFeatureCollection
    from ._models_py3 import GeoJsonFeatureCollectionData
    from ._models_py3 import GeoJsonFeatureData
    from ._models_py3 import GeoJsonGeometry
    from ._models_py3 import GeoJsonGeometryCollection
    from ._models_py3 import GeoJsonGeometryCollectionData
    from ._models_py3 import GeoJsonLineString
    from ._models_py3 import GeoJsonLineStringData
    from ._models_py3 import GeoJsonMultiLineString
    from ._models_py3 import GeoJsonMultiLineStringData
    from ._models_py3 import GeoJsonMultiPoint
    from ._models_py3 import GeoJsonMultiPointData
    from ._models_py3 import GeoJsonMultiPolygon
    from ._models_py3 import GeoJsonMultiPolygonData
    from ._models_py3 import GeoJsonObject
    from ._models_py3 import GeoJsonPoint
    from ._models_py3 import GeoJsonPointData
    from ._models_py3 import GeoJsonPolygon
    from ._models_py3 import GeoJsonPolygonData
    from ._models_py3 import GeofenceGeometry
    from ._models_py3 import GeofenceResponse
    from ._models_py3 import GreatCircleDistanceResponse
    from ._models_py3 import GreatCircleDistanceResponseResult
    from ._models_py3 import GreatCircleDistanceResponseSummary
    from ._models_py3 import PointInPolygonResponse
    from ._models_py3 import PointInPolygonResult
    from ._models_py3 import PointInPolygonSummary
    from ._models_py3 import SpatialCoordinate
except (SyntaxError, ImportError):
    from ._models import BufferRequestBody  # type: ignore
    from ._models import BufferResponse  # type: ignore
    from ._models import BufferResponseSummary  # type: ignore
    from ._models import ClosestPointResponse  # type: ignore
    from ._models import ClosestPointResultEntry  # type: ignore
    from ._models import ClosestPointSummary  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import GeoJsonFeature  # type: ignore
    from ._models import GeoJsonFeatureCollection  # type: ignore
    from ._models import GeoJsonFeatureCollectionData  # type: ignore
    from ._models import GeoJsonFeatureData  # type: ignore
    from ._models import GeoJsonGeometry  # type: ignore
    from ._models import GeoJsonGeometryCollection  # type: ignore
    from ._models import GeoJsonGeometryCollectionData  # type: ignore
    from ._models import GeoJsonLineString  # type: ignore
    from ._models import GeoJsonLineStringData  # type: ignore
    from ._models import GeoJsonMultiLineString  # type: ignore
    from ._models import GeoJsonMultiLineStringData  # type: ignore
    from ._models import GeoJsonMultiPoint  # type: ignore
    from ._models import GeoJsonMultiPointData  # type: ignore
    from ._models import GeoJsonMultiPolygon  # type: ignore
    from ._models import GeoJsonMultiPolygonData  # type: ignore
    from ._models import GeoJsonObject  # type: ignore
    from ._models import GeoJsonPoint  # type: ignore
    from ._models import GeoJsonPointData  # type: ignore
    from ._models import GeoJsonPolygon  # type: ignore
    from ._models import GeoJsonPolygonData  # type: ignore
    from ._models import GeofenceGeometry  # type: ignore
    from ._models import GeofenceResponse  # type: ignore
    from ._models import GreatCircleDistanceResponse  # type: ignore
    from ._models import GreatCircleDistanceResponseResult  # type: ignore
    from ._models import GreatCircleDistanceResponseSummary  # type: ignore
    from ._models import PointInPolygonResponse  # type: ignore
    from ._models import PointInPolygonResult  # type: ignore
    from ._models import PointInPolygonSummary  # type: ignore
    from ._models import SpatialCoordinate  # type: ignore

from ._maps_spatial_client_enums import (
    GeoJsonObjectType,
    GeofenceMode,
    GeographicResourceLocation,
    Geography,
    ResponseFormat,
)

__all__ = [
    'BufferRequestBody',
    'BufferResponse',
    'BufferResponseSummary',
    'ClosestPointResponse',
    'ClosestPointResultEntry',
    'ClosestPointSummary',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'GeoJsonFeature',
    'GeoJsonFeatureCollection',
    'GeoJsonFeatureCollectionData',
    'GeoJsonFeatureData',
    'GeoJsonGeometry',
    'GeoJsonGeometryCollection',
    'GeoJsonGeometryCollectionData',
    'GeoJsonLineString',
    'GeoJsonLineStringData',
    'GeoJsonMultiLineString',
    'GeoJsonMultiLineStringData',
    'GeoJsonMultiPoint',
    'GeoJsonMultiPointData',
    'GeoJsonMultiPolygon',
    'GeoJsonMultiPolygonData',
    'GeoJsonObject',
    'GeoJsonPoint',
    'GeoJsonPointData',
    'GeoJsonPolygon',
    'GeoJsonPolygonData',
    'GeofenceGeometry',
    'GeofenceResponse',
    'GreatCircleDistanceResponse',
    'GreatCircleDistanceResponseResult',
    'GreatCircleDistanceResponseSummary',
    'PointInPolygonResponse',
    'PointInPolygonResult',
    'PointInPolygonSummary',
    'SpatialCoordinate',
    'GeoJsonObjectType',
    'GeofenceMode',
    'GeographicResourceLocation',
    'Geography',
    'ResponseFormat',
]
