# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AliasListItem
    from ._models_py3 import AliasListResponse
    from ._models_py3 import AliasesCreateResponse
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
except (SyntaxError, ImportError):
    from ._models import AliasListItem  # type: ignore
    from ._models import AliasListResponse  # type: ignore
    from ._models import AliasesCreateResponse  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore

from ._maps_alias_client_enums import (
    GeographicResourceLocation,
    Geography,
)

__all__ = [
    'AliasListItem',
    'AliasListResponse',
    'AliasesCreateResponse',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'GeographicResourceLocation',
    'Geography',
]
