# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Optional

from azure.core.exceptions import HttpResponseError
import msrest.serialization


class AliasesCreateResponse(msrest.serialization.Model):
    """The response model for the Alias Create API for the case when the alias was successfully created.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar created_timestamp: The created timestamp for the alias.
    :vartype created_timestamp: str
    :ivar alias_id: The id for the alias.
    :vartype alias_id: str
    :ivar creator_data_item_id: The id for the creator data item that this alias references (could
     be null if the alias has not been assigned).
    :vartype creator_data_item_id: str
    :ivar last_updated_timestamp: The timestamp of the last time the alias was assigned.
    :vartype last_updated_timestamp: str
    """

    _validation = {
        'created_timestamp': {'readonly': True},
        'alias_id': {'readonly': True},
        'creator_data_item_id': {'readonly': True},
        'last_updated_timestamp': {'readonly': True},
    }

    _attribute_map = {
        'created_timestamp': {'key': 'createdTimestamp', 'type': 'str'},
        'alias_id': {'key': 'aliasId', 'type': 'str'},
        'creator_data_item_id': {'key': 'creatorDataItemId', 'type': 'str'},
        'last_updated_timestamp': {'key': 'lastUpdatedTimestamp', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(AliasesCreateResponse, self).__init__(**kwargs)
        self.created_timestamp = None
        self.alias_id = None
        self.creator_data_item_id = None
        self.last_updated_timestamp = None


class AliasListItem(msrest.serialization.Model):
    """Detailed information for the alias.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar created_timestamp: The created timestamp for the alias.
    :vartype created_timestamp: str
    :ivar alias_id: The id for the alias.
    :vartype alias_id: str
    :ivar creator_data_item_id: The id for the creator data item that this alias references (could
     be null if the alias has not been assigned).
    :vartype creator_data_item_id: str
    :ivar last_updated_timestamp: The timestamp of the last time the alias was assigned.
    :vartype last_updated_timestamp: str
    """

    _validation = {
        'created_timestamp': {'readonly': True},
        'alias_id': {'readonly': True},
        'creator_data_item_id': {'readonly': True},
        'last_updated_timestamp': {'readonly': True},
    }

    _attribute_map = {
        'created_timestamp': {'key': 'createdTimestamp', 'type': 'str'},
        'alias_id': {'key': 'aliasId', 'type': 'str'},
        'creator_data_item_id': {'key': 'creatorDataItemId', 'type': 'str'},
        'last_updated_timestamp': {'key': 'lastUpdatedTimestamp', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(AliasListItem, self).__init__(**kwargs)
        self.created_timestamp = None
        self.alias_id = None
        self.creator_data_item_id = None
        self.last_updated_timestamp = None


class AliasListResponse(msrest.serialization.Model):
    """The response model for the List API. Returns a list of all the previously created aliases.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar aliases: A list of all the previously created aliases.
    :vartype aliases: list[~azure.maps.alias.models.AliasListItem]
    :ivar next_link: If present, the location of the next page of data.
    :vartype next_link: str
    """

    _validation = {
        'aliases': {'readonly': True},
        'next_link': {'readonly': True},
    }

    _attribute_map = {
        'aliases': {'key': 'aliases', 'type': '[AliasListItem]'},
        'next_link': {'key': 'nextLink', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(AliasListResponse, self).__init__(**kwargs)
        self.aliases = None
        self.next_link = None


class ErrorAdditionalInfo(msrest.serialization.Model):
    """The resource management error additional info.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: any
    """

    _validation = {
        'type': {'readonly': True},
        'info': {'readonly': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'info': {'key': 'info', 'type': 'object'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorAdditionalInfo, self).__init__(**kwargs)
        self.type = None
        self.info = None


class ErrorDetail(msrest.serialization.Model):
    """The error detail.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.maps.alias.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.maps.alias.models.ErrorAdditionalInfo]
    """

    _validation = {
        'code': {'readonly': True},
        'message': {'readonly': True},
        'target': {'readonly': True},
        'details': {'readonly': True},
        'additional_info': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'details': {'key': 'details', 'type': '[ErrorDetail]'},
        'additional_info': {'key': 'additionalInfo', 'type': '[ErrorAdditionalInfo]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorDetail, self).__init__(**kwargs)
        self.code = None
        self.message = None
        self.target = None
        self.details = None
        self.additional_info = None


class ErrorResponse(msrest.serialization.Model):
    """Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).

    :param error: The error object.
    :type error: ~azure.maps.alias.models.ErrorDetail
    """

    _attribute_map = {
        'error': {'key': 'error', 'type': 'ErrorDetail'},
    }

    def __init__(
        self,
        *,
        error: Optional["ErrorDetail"] = None,
        **kwargs
    ):
        super(ErrorResponse, self).__init__(**kwargs)
        self.error = error
