# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AgencyDetails
    from ._models_py3 import AlertDescription
    from ._models_py3 import AlertDetail
    from ._models_py3 import AlertInformation
    from ._models_py3 import CoordinatesPair
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import FareDetail
    from ._models_py3 import FarePrice
    from ._models_py3 import FareTicket
    from ._models_py3 import GeoJsonFeature
    from ._models_py3 import GeoJsonFeatureCollection
    from ._models_py3 import GeoJsonFeatureCollectionData
    from ._models_py3 import GeoJsonFeatureData
    from ._models_py3 import GeoJsonGeometry
    from ._models_py3 import GeoJsonGeometryCollection
    from ._models_py3 import GeoJsonGeometryCollectionData
    from ._models_py3 import GeoJsonLineString
    from ._models_py3 import GeoJsonLineStringData
    from ._models_py3 import GeoJsonMultiLineString
    from ._models_py3 import GeoJsonMultiLineStringData
    from ._models_py3 import GeoJsonMultiPoint
    from ._models_py3 import GeoJsonMultiPointData
    from ._models_py3 import GeoJsonMultiPolygon
    from ._models_py3 import GeoJsonMultiPolygonData
    from ._models_py3 import GeoJsonObject
    from ._models_py3 import GeoJsonPoint
    from ._models_py3 import GeoJsonPointData
    from ._models_py3 import GeoJsonPolygon
    from ._models_py3 import GeoJsonPolygonData
    from ._models_py3 import ItineraryFare
    from ._models_py3 import ItineraryLeg
    from ._models_py3 import ItineraryLine
    from ._models_py3 import ItineraryLineGroup
    from ._models_py3 import ItineraryPattern
    from ._models_py3 import ItineraryResult
    from ._models_py3 import ItineraryStep
    from ._models_py3 import LegFare
    from ._models_py3 import LegPoint
    from ._models_py3 import LegStop
    from ._models_py3 import LineArrival
    from ._models_py3 import MetroAreaInfoResponse
    from ._models_py3 import MetroAreaResponse
    from ._models_py3 import MetroAreaResult
    from ._models_py3 import NearbyTransitResponse
    from ._models_py3 import RealTimeArrivalResult
    from ._models_py3 import RealTimeArrivalsResponse
    from ._models_py3 import ResultViewport
    from ._models_py3 import RouteItineraryLeg
    from ._models_py3 import TransitItineraryResponse
    from ._models_py3 import TransitLineInfoResponse
    from ._models_py3 import TransitObjectResult
    from ._models_py3 import TransitRouteResponse
    from ._models_py3 import TransitStopInfoResponse
    from ._models_py3 import TransitTypeResult
    from ._models_py3 import WalkingDirection
except (SyntaxError, ImportError):
    from ._models import AgencyDetails  # type: ignore
    from ._models import AlertDescription  # type: ignore
    from ._models import AlertDetail  # type: ignore
    from ._models import AlertInformation  # type: ignore
    from ._models import CoordinatesPair  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import FareDetail  # type: ignore
    from ._models import FarePrice  # type: ignore
    from ._models import FareTicket  # type: ignore
    from ._models import GeoJsonFeature  # type: ignore
    from ._models import GeoJsonFeatureCollection  # type: ignore
    from ._models import GeoJsonFeatureCollectionData  # type: ignore
    from ._models import GeoJsonFeatureData  # type: ignore
    from ._models import GeoJsonGeometry  # type: ignore
    from ._models import GeoJsonGeometryCollection  # type: ignore
    from ._models import GeoJsonGeometryCollectionData  # type: ignore
    from ._models import GeoJsonLineString  # type: ignore
    from ._models import GeoJsonLineStringData  # type: ignore
    from ._models import GeoJsonMultiLineString  # type: ignore
    from ._models import GeoJsonMultiLineStringData  # type: ignore
    from ._models import GeoJsonMultiPoint  # type: ignore
    from ._models import GeoJsonMultiPointData  # type: ignore
    from ._models import GeoJsonMultiPolygon  # type: ignore
    from ._models import GeoJsonMultiPolygonData  # type: ignore
    from ._models import GeoJsonObject  # type: ignore
    from ._models import GeoJsonPoint  # type: ignore
    from ._models import GeoJsonPointData  # type: ignore
    from ._models import GeoJsonPolygon  # type: ignore
    from ._models import GeoJsonPolygonData  # type: ignore
    from ._models import ItineraryFare  # type: ignore
    from ._models import ItineraryLeg  # type: ignore
    from ._models import ItineraryLine  # type: ignore
    from ._models import ItineraryLineGroup  # type: ignore
    from ._models import ItineraryPattern  # type: ignore
    from ._models import ItineraryResult  # type: ignore
    from ._models import ItineraryStep  # type: ignore
    from ._models import LegFare  # type: ignore
    from ._models import LegPoint  # type: ignore
    from ._models import LegStop  # type: ignore
    from ._models import LineArrival  # type: ignore
    from ._models import MetroAreaInfoResponse  # type: ignore
    from ._models import MetroAreaResponse  # type: ignore
    from ._models import MetroAreaResult  # type: ignore
    from ._models import NearbyTransitResponse  # type: ignore
    from ._models import RealTimeArrivalResult  # type: ignore
    from ._models import RealTimeArrivalsResponse  # type: ignore
    from ._models import ResultViewport  # type: ignore
    from ._models import RouteItineraryLeg  # type: ignore
    from ._models import TransitItineraryResponse  # type: ignore
    from ._models import TransitLineInfoResponse  # type: ignore
    from ._models import TransitObjectResult  # type: ignore
    from ._models import TransitRouteResponse  # type: ignore
    from ._models import TransitStopInfoResponse  # type: ignore
    from ._models import TransitTypeResult  # type: ignore
    from ._models import WalkingDirection  # type: ignore

from ._maps_mobility_client_enums import (
    AbsoluteDirection,
    AgencyType,
    DestinationType,
    GeoJsonObjectType,
    GeographicResourceLocation,
    Geography,
    LegType,
    MetroAreaDetailType,
    MetroAreaQueryType,
    ModeType,
    OriginType,
    RealTimeArrivalsQueryType,
    RelativeDirection,
    ResponseFormat,
    ScheduleType,
    StopQueryType,
    TimeType,
    TransitItineraryDetailType,
    TransitLineDetailType,
    TransitRouteType,
    TransitStopDetailType,
    TransitStopQueryType,
    TransitType,
    TransitTypeFilter,
)

__all__ = [
    'AgencyDetails',
    'AlertDescription',
    'AlertDetail',
    'AlertInformation',
    'CoordinatesPair',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'FareDetail',
    'FarePrice',
    'FareTicket',
    'GeoJsonFeature',
    'GeoJsonFeatureCollection',
    'GeoJsonFeatureCollectionData',
    'GeoJsonFeatureData',
    'GeoJsonGeometry',
    'GeoJsonGeometryCollection',
    'GeoJsonGeometryCollectionData',
    'GeoJsonLineString',
    'GeoJsonLineStringData',
    'GeoJsonMultiLineString',
    'GeoJsonMultiLineStringData',
    'GeoJsonMultiPoint',
    'GeoJsonMultiPointData',
    'GeoJsonMultiPolygon',
    'GeoJsonMultiPolygonData',
    'GeoJsonObject',
    'GeoJsonPoint',
    'GeoJsonPointData',
    'GeoJsonPolygon',
    'GeoJsonPolygonData',
    'ItineraryFare',
    'ItineraryLeg',
    'ItineraryLine',
    'ItineraryLineGroup',
    'ItineraryPattern',
    'ItineraryResult',
    'ItineraryStep',
    'LegFare',
    'LegPoint',
    'LegStop',
    'LineArrival',
    'MetroAreaInfoResponse',
    'MetroAreaResponse',
    'MetroAreaResult',
    'NearbyTransitResponse',
    'RealTimeArrivalResult',
    'RealTimeArrivalsResponse',
    'ResultViewport',
    'RouteItineraryLeg',
    'TransitItineraryResponse',
    'TransitLineInfoResponse',
    'TransitObjectResult',
    'TransitRouteResponse',
    'TransitStopInfoResponse',
    'TransitTypeResult',
    'WalkingDirection',
    'AbsoluteDirection',
    'AgencyType',
    'DestinationType',
    'GeoJsonObjectType',
    'GeographicResourceLocation',
    'Geography',
    'LegType',
    'MetroAreaDetailType',
    'MetroAreaQueryType',
    'ModeType',
    'OriginType',
    'RealTimeArrivalsQueryType',
    'RelativeDirection',
    'ResponseFormat',
    'ScheduleType',
    'StopQueryType',
    'TimeType',
    'TransitItineraryDetailType',
    'TransitLineDetailType',
    'TransitRouteType',
    'TransitStopDetailType',
    'TransitStopQueryType',
    'TransitType',
    'TransitTypeFilter',
]
