# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import ConversionListDetailInfo
    from ._models_py3 import ConversionListResponse
    from ._models_py3 import ErrorAdditionalInfo
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorResponse
    from ._models_py3 import LongRunningOperationResult
except (SyntaxError, ImportError):
    from ._models import ConversionListDetailInfo  # type: ignore
    from ._models import ConversionListResponse  # type: ignore
    from ._models import ErrorAdditionalInfo  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import LongRunningOperationResult  # type: ignore

from ._maps_conversion_client_enums import (
    GeographicResourceLocation,
    Geography,
    LroStatus,
)

__all__ = [
    'ConversionListDetailInfo',
    'ConversionListResponse',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorResponse',
    'LongRunningOperationResult',
    'GeographicResourceLocation',
    'Geography',
    'LroStatus',
]
