# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.core.exceptions import HttpResponseError
import msrest.serialization


class ConversionListDetailInfo(msrest.serialization.Model):
    """Detail information for the conversion requests.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar conversion_id: A unique id that represents the artifact of a *successfully* completed
     conversion process.
    :vartype conversion_id: str
    :ivar ontology: The ontology version of this dataset.
    :vartype ontology: str
    :ivar udid: The unique id of the content provided to create this conversion.
    :vartype udid: str
    :ivar created: The date and time of this conversion.
    :vartype created: str
    :ivar description: User provided description of the content being converted.
    :vartype description: str
    :ivar feature_counts: A summary of feature counts in this conversion.
    :vartype feature_counts: any
    """

    _validation = {
        'conversion_id': {'readonly': True},
        'ontology': {'readonly': True},
        'udid': {'readonly': True},
        'created': {'readonly': True},
        'description': {'readonly': True},
        'feature_counts': {'readonly': True},
    }

    _attribute_map = {
        'conversion_id': {'key': 'conversionId', 'type': 'str'},
        'ontology': {'key': 'ontology', 'type': 'str'},
        'udid': {'key': 'udid', 'type': 'str'},
        'created': {'key': 'created', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'feature_counts': {'key': 'featureCounts', 'type': 'object'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ConversionListDetailInfo, self).__init__(**kwargs)
        self.conversion_id = None
        self.ontology = None
        self.udid = None
        self.created = None
        self.description = None
        self.feature_counts = None


class ConversionListResponse(msrest.serialization.Model):
    """The response model for the Conversion List API.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar conversions: A list of all the previously submitted conversion requests.
    :vartype conversions: list[~azure.maps.conversion.models.ConversionListDetailInfo]
    :ivar next_link: If present, the location of the next page of data.
    :vartype next_link: str
    """

    _validation = {
        'conversions': {'readonly': True},
        'next_link': {'readonly': True},
    }

    _attribute_map = {
        'conversions': {'key': 'conversions', 'type': '[ConversionListDetailInfo]'},
        'next_link': {'key': 'nextLink', 'type': 'str'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ConversionListResponse, self).__init__(**kwargs)
        self.conversions = None
        self.next_link = None


class ErrorAdditionalInfo(msrest.serialization.Model):
    """The resource management error additional info.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: any
    """

    _validation = {
        'type': {'readonly': True},
        'info': {'readonly': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'info': {'key': 'info', 'type': 'object'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorAdditionalInfo, self).__init__(**kwargs)
        self.type = None
        self.info = None


class ErrorDetail(msrest.serialization.Model):
    """The error detail.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.maps.conversion.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.maps.conversion.models.ErrorAdditionalInfo]
    """

    _validation = {
        'code': {'readonly': True},
        'message': {'readonly': True},
        'target': {'readonly': True},
        'details': {'readonly': True},
        'additional_info': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'details': {'key': 'details', 'type': '[ErrorDetail]'},
        'additional_info': {'key': 'additionalInfo', 'type': '[ErrorAdditionalInfo]'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorDetail, self).__init__(**kwargs)
        self.code = None
        self.message = None
        self.target = None
        self.details = None
        self.additional_info = None


class ErrorResponse(msrest.serialization.Model):
    """Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).

    :param error: The error object.
    :type error: ~azure.maps.conversion.models.ErrorDetail
    """

    _attribute_map = {
        'error': {'key': 'error', 'type': 'ErrorDetail'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(ErrorResponse, self).__init__(**kwargs)
        self.error = kwargs.get('error', None)


class LongRunningOperationResult(msrest.serialization.Model):
    """The response model for a Long-Running Operations API.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param operation_id: The Id for this long-running operation.
    :type operation_id: str
    :ivar status: The status state of the request. Possible values include: "NotStarted",
     "Running", "Failed", "Succeeded".
    :vartype status: str or ~azure.maps.conversion.models.LroStatus
    :ivar created: The created timestamp.
    :vartype created: str
    :ivar resource_location: The location URI for details about the created resource. This is only
     provided when the request was successfully completed.
    :vartype resource_location: str
    :param error: The error detail.
    :type error: ~azure.maps.conversion.models.ErrorDetail
    :param warning: The error detail.
    :type warning: ~azure.maps.conversion.models.ErrorDetail
    """

    _validation = {
        'status': {'readonly': True},
        'created': {'readonly': True},
        'resource_location': {'readonly': True},
    }

    _attribute_map = {
        'operation_id': {'key': 'operationId', 'type': 'str'},
        'status': {'key': 'status', 'type': 'str'},
        'created': {'key': 'created', 'type': 'str'},
        'resource_location': {'key': 'resourceLocation', 'type': 'str'},
        'error': {'key': 'error', 'type': 'ErrorDetail'},
        'warning': {'key': 'warning', 'type': 'ErrorDetail'},
    }

    def __init__(
        self,
        **kwargs
    ):
        super(LongRunningOperationResult, self).__init__(**kwargs)
        self.operation_id = kwargs.get('operation_id', None)
        self.status = None
        self.created = None
        self.resource_location = None
        self.error = kwargs.get('error', None)
        self.warning = kwargs.get('warning', None)
